#+SETUPFILE: preamble.org

* What's New							   :noexport:

GPG 16 appears to suggest that the collaborator list is no longer part of the [[bio.org][bio sketch]] (see http://www.nsf.gov/pubs/policydocs/pappguide/nsf16001/gpg_2.jsp#IIC1e ).

* Instructions 							   :noexport:

In FastLane, biographical sketches for senior personnel may no longer be grouped together and uploaded in a single PDF file associated with the PI. Each individual’s biographical sketch must be uploaded as a single PDF file or inserted as text associated with that individual.

NOTE: Bio sketches for "Other Personnel" may be included for post-docs, other professionsal, and student research assistants. See [[GPG.pdf]]. Equipment proposals must provide bio sketches for each auxiliary user, w/ publication list. See GPG.pdf.

A biographical sketch (limited to two pages) is required for each individual identified as senior personnel. (See GPG Exhibit II-7 for the definitions of Senior Personnel.) Proposers may elect to use third-party solutions, such as NIH’s SciENcv to develop and maintain their biographical sketch. However, proposers are advised that they are still responsible for ensuring that biographical sketches created using third-party solutions are compliant with NSF proposal preparation requirements.

 The following information must be provided in the order and format specified below. Inclusion of additional information beyond that specified below may result in the proposal being returned without review.

* Biographical Sketch: Your Name

** Professional Preparation

A list of the individual’s undergraduate and graduate education and postdoctoral training (including location) as indicated below:

| Undergraduate Institution(s)   | Major   | Degree YYYY   |
| Graduate Institution(s)        | Major   | Degree YYYY   |
| Postdoctoral Institution(s)    | Area    | YYYY-YYYY     |

** Appointments

A list, in reverse chronological order, of all the individual’s academic/professional appointments beginning with the current appointment.

| Institution   | Role   | YYYY --        |
| Institution   | Role   | YYYY -- YYYY   |
| Institution   | Role   | YYYY -- YYYY   |

** Instructions: Products					   :noexport:

A list of: (i) up to five products most closely related to the proposed project; and (ii) up to five other significant products, whether or not related to the proposed project. Acceptable products must be citable and accessible including but not limited to publications, data sets, software, patents, and copyrights. Unacceptable products are unpublished documents not yet submitted for publication, invited lectures, and additional lists of products. Only the list of ten will be used in the review of the proposal.

Each product must include full citation information including (where applicable and practicable) names of all authors, date of publication or release, title, title of enclosing work such as journal or book, volume, issue, pages, website and URL or other Persistent Identifier.

If only publications are included, the heading “Publications” may be used for this section of the Biographical Sketch.
   
** Products

Hint: can auto-generate reference list w/ LaTeX with:
[[nocite:CiteKey]]
\printbibliography[heading=none]

** Instructions: Synergistic Activities				   :noexport:

A list of up to five examples that demonstrate the broader impact of the individual’s professional and scholarly activities that focuses on the integration and transfer of knowledge as well as its creation. Examples could include, among others: innovations in teaching and training (e.g., development of curricular materials and pedagogical methods); contributions to the science of learning; development and/or refinement of research tools; computation methodologies, and algorithms for problem-solving; development of databases to support research and education; broadening the participation of groups underrepresented in STEM; and service to the scientific and engineering community outside of the individual’s immediate organization.

** Synergistic Activities


1. *Something*:

2. *Other Thing*:

