#+SETUPFILE: preamble.org

* Instructions							   :noexport:

https://www.nsf.gov/pubs/policydocs/pappg17_1/pappg_2.jsp#IIC2d

* Project Description

* Broader Impacts

* Results From Prior NSF Support

https://www.nsf.gov/pubs/policydocs/pappg17_1/pappg_2.jsp#IIC2diii

(a)	the NSF award number, amount and period of support;

(b)	the title of the project;

(c)	a summary of the results of the completed work, including accomplishments, supported by the award. The results must be separately described under two distinct headings: Intellectual Merit and Broader Impacts;

(d)	a listing of the publications resulting from the NSF award (a complete bibliographic citation for each publication must be provided either in this section or in the References Cited section of the proposal); if none, state “No publications were produced under this award.”

(e)	evidence of research products and their availability, including, but not limited to: data, publications, samples, physical collections, software, and models, as described in any Data Management Plan; and

(f)	if the proposal is for renewed support, a description of the relation of the completed work to the proposed work.

If the project was recently awarded and therefore no new results exist, describe the major goals and broader impacts of the project. Note that the proposal may contain up to five pages to describe the results. Results may be summarized in fewer than five pages, which would give the balance of the 15 pages for the Project Description.
