#+SETUPFILE: preamble.org

* Instructions							   :noexport:

15 page limit

The Project Description should provide a clear statement of the work to be undertaken and must include the objectives for the period of the proposed work and expected significance; the relationship of this work to the present state of knowledge in the field, as well as to work in progress by the PI under other support.

The Project Description should outline the general plan of work, including the broad design of activities to be undertaken, and, where appropriate, provide a clear description of experimental methods and procedures. Proposers should address what they want to do, why they want to do it, how they plan to do it, how they will know if they succeed, and what benefits could accrue if the project is successful. The project activities may be based on previously established and/or innovative methods and approaches, but in either case must be well justified. These issues apply to both the technical aspects of the proposal and the way in which the project may make broader contributions.

The Project Description must contain, as a separate section within the narrative, a section labeled “Broader Impacts”. This section should provide a discussion of the broader impacts of the proposed activities. Broader impacts may be accomplished through the research itself, through the activities that are directly related to specific research projects, or through activities that are supported by, but are complementary to the project. NSF values the advancement of scientific knowledge and activities that contribute to the achievement of societally relevant outcomes. Such outcomes include, but are not limited to: full participation of women, persons with disabilities, and underrepresented minorities in science, technology, engineering, and mathematics (STEM); improved STEM education and educator development at any level; increased public scientific literacy and public engagement with science and technology; improved well-being of individuals in society; development of a diverse, globally competitive STEM workforce; increased partnerships between academia, industry, and others; improved national security; increased economic competitiveness of the US; and enhanced infrastructure for research and education.

Plans for data management and sharing of the products of research, including preservation, documentation, and sharing of data, samples, physical collections, curriculum materials and other related research and education products should be described in the Special Information and Supplementary Documentation section of the proposal (see GPG Chapter II.C.2.j for additional instructions for preparation of this section).

* Project Description

* Broader Impacts

* Instructions: Results From Prior NSF Support			   :noexport:

If any PI or co-PI identified on the proposal has received NSF funding with a start date17 in the past five years (including any current funding and no cost extensions), information on the award is required for each PI and co-PI, regardless of whether the support was directly related to the proposal or not. In cases where the PI or co-PI has received more than one award (excluding amendments to existing awards), they need only report on the one award most closely related to the proposal. Funding includes not just salary support, but any funding awarded by NSF. NSF awards such as standard or continuing grants, Graduate Research Fellowship, Major Research Instrumentation, travel, conference, and center awards, etc., are subject to this requirement.

Reviewers will be asked to comment on the quality of the prior work described in this section of the proposal. Note that the proposal may contain up to five pages to describe the results. Results may be summarized in fewer than five pages, which would give the balance of the 15 pages for the Project Description.


+ (a) the NSF award number, amount and period of support;
+ (b) the title of the project;
+ (c) a summary of the results of the completed work, including accomplishments, supported by the award. The results must be separately described under two distinct headings: Intellectual Merit and Broader Impacts;
+ (d) a listing of the publications resulting from the NSF award (a complete bibliographic citation for each publication must be provided either in this section or in the References Cited section of the proposal); if none, state “No publications were produced under this award.”
+ (e) evidence of research products and their availability, including, but not limited to: data, publications, samples, physical collections, software, and models, as described in any Data Management Plan; and
+ (f) if the proposal is for renewed support, a description of the relation of the completed work to the proposed work.

* Results From Prior NSF Support
